### ISSUE TITLE
"kinetics" config?

### ISSUE THREAD

**Issue by petteriTeikari** [limaosen0/AS-GCN#10]
Hi,

Do you happen to have the `kinetics` config available to share so that your results are easier to reproduce as your repo seemed to contain only the `NTU-RGBD` configs?

Thanks

**Comment by petteriTeikari** [comment]
Essentially needed to change three parameters:

```yaml
num_class: 400
layout: 'openpose'
node_num: 18
```

I used the following `train_aim.yaml`

```yaml
work_dir: ./work_dir/recognition/kinetics/AS_GCN

feeder: feeder.feeder.Feeder
train_feeder_args:
  data_path: ../data/kinetics/train_data_joint.npy
  label_path: ../data/kinetics/train_label.pkl
  random_move: True
  repeat_pad: True
  down_sample: True
test_feeder_args:
  data_path: ../data/kinetics/val_data_joint.npy
  label_path: ../data/kinetics/val_label.pkl
  random_move: False
  repeat_pad: True
  down_sample: True

model1: net.as_gcn.Model
model1_args:
  in_channels: 3
  num_class: 400
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'openpose'
    strategy: 'spatial'
    max_hop: 4

model2: net.utils.adj_learn.AdjacencyLearn
model2_args:
  n_in_enc: 150
  n_hid_enc: 128
  edge_types: 3
  n_in_dec: 3
  n_hid_dec: 128
  node_num: 18

weight_decay: 0.0001
base_lr1: 0.1
base_lr2: 0.0005
step: [50, 70, 90]

device: [0]
batch_size: 32
test_batch_size: 32
start_epoch: 0
num_epoch: 10
num_worker: 4

max_hop_dir: max_hop_4
lamda_act_dir: lamda_05
lamda_act: 0.5
```

and `train.yaml` do they seem correct to you

```yaml
work_dir: ./work_dir/recognition/kinetics/AS_GCN

weights1: ./work_dir/recognition/kinetics/AS_GCN/max_hop_4/lamda_05/epoch9_model1.pt
weights2: ./work_dir/recognition/kinetics/AS_GCN/max_hop_4/lamda_05/epoch9_model2.pt

feeder: feeder.feeder.Feeder
train_feeder_args:
  data_path: ../data/kinetics/train_data_joint.npy
  label_path: ../data/kinetics/train_label.pkl
  random_move: True
  repeat_pad: True
  down_sample: True
test_feeder_args:
  data_path: ../data/kinetics/val_data_joint.npy
  label_path: ../data/kinetics/val_label.pkl
  random_move: False
  repeat_pad: True
  down_sample: True

model1: net.as_gcn.Model
model1_args:
  in_channels: 3
  num_class: 400 
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'kinetics'
    strategy: 'openpose'
    max_hop: 4

model2: net.utils.adj_learn.AdjacencyLearn
model2_args:
  n_in_enc: 150
  n_hid_enc: 128
  edge_types: 3
  n_in_dec: 3
  n_hid_dec: 128
  node_num: 18

weight_decay: 0.0001
base_lr1: 0.1
base_lr2: 0.0005
step: [50, 70, 90]

device: [0]
batch_size: 32
test_batch_size: 32
start_epoch: 10
num_epoch: 100
num_worker: 4

max_hop_dir: max_hop_4
lamda_act_dir: lamda_05
lamda_act: 0.5
```
